<?php
return array (
  2 => 
  array (
    'modelid' => '2',
    'siteid' => '1',
    'name' => '新闻模型',
    'description' => '新闻专用模型',
    'tablename' => 'news',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_add_template' => 'content_add',
    'admin_edit_template' => 'content_edit',
    'admin_list_template' => 'content_list',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  3 => 
  array (
    'modelid' => '3',
    'siteid' => '1',
    'name' => '视频模型',
    'description' => '视频专用模型',
    'tablename' => 'video',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_video',
    'list_template' => 'list_video',
    'show_template' => 'show_video',
    'js_template' => '',
    'admin_add_template' => 'content_add_video',
    'admin_edit_template' => 'content_edit_video',
    'admin_list_template' => 'content_list_video',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  7 => 
  array (
    'modelid' => '7',
    'siteid' => '1',
    'name' => '直播模型',
    'description' => '直播专用模型',
    'tablename' => 'direct',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_video',
    'list_template' => 'list_video',
    'show_template' => 'show_video_direct',
    'js_template' => '',
    'admin_add_template' => '',
    'admin_edit_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  9 => 
  array (
    'modelid' => '9',
    'siteid' => '1',
    'name' => '工作人员名片',
    'description' => '工作人员名片模型',
    'tablename' => 'jobs',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list_reporter',
    'show_template' => 'show_reporter',
    'js_template' => '',
    'admin_add_template' => '',
    'admin_edit_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  10 => 
  array (
    'modelid' => '10',
    'siteid' => '1',
    'name' => '合作单位模型',
    'description' => '合作单位专用模型',
    'tablename' => 'sponsor',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list_sponsor',
    'show_template' => 'show',
    'js_template' => '',
    'admin_add_template' => '',
    'admin_edit_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
);
?>